#! /bin/bash

echo "**********************"
echo "RADIUSS Shared CI Test"
echo "**********************"
echo ""
echo "Variables of interest:"
: "${CI_MACHINE:?CI_MACHINE must be set by the machine component}"
echo "CI_MACHINE: ${CI_MACHINE}"
